version: "3.9"
services:
  woofwalks-api:
    build:
      context: ../woofwalks-api
      dockerfile: Dockerfile
    container_name: woofwalks-api
    volumes:
      - woofwalks-api-data:/var/www/symfony
    ports:
      - "8000:8000"
    environment:
      APP_ENV: dev
      DATABASE_URL: mysql://root:LiloSisko33!@db:3306/woofwalks
    depends_on:
      - db
    networks:
      - woofwalks-network

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: LiloSisko33!
      MYSQL_DATABASE: woofwalks
    ports:
      - "3307:3306"
    networks:
      - woofwalks-network
    volumes:
      - db_data:/var/lib/mysql

  react-app:
    build:
      context: ../woofwalks
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    networks:
      - woofwalks-network
    depends_on:
      - woofwalks-api
    volumes:
      - ../woofwalks:/app

volumes: # Définitions des volumes nommés (au bon niveau)
  woofwalks-api-data:
  db_data:

networks:
  woofwalks-network:
    driver: bridge
