controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
# upload_file:
#   path: /upload
#   controller: App\Controller\UploadController::upload
#   methods: [POST]
