# nelmio_cors:
#     defaults:
#         origin_regex: true
#         allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#         allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#         allow_headers: ['Content-Type', 'Authorization']
#         expose_headers: ['Link']
#         max_age: 3600
#     paths:
#         '^/': null
nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ["https://localhost:3000"] # Votre frontend React

    allow_methods: ["POST", "GET", "OPTIONS", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    max_age: 3600
  paths:
    "^/api/": # Applique CORS uniquement aux routes de l'API
      allow_origin: ["https://localhost:3000"] # Frontend React en HTTPS
      allow_methods: ["POST", "GET", "OPTIONS", "PUT", "PATCH", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_credentials: true
